# negative_sampling の挙動観察
目的：`torch_geometric.utils.negatie_sampling` の挙動を調べる

In [1]:
import torch_geometric

In [ ]:
---
## 適当なグラフを与え，negative_sampling を実行する

In [3]:
# 適当なグラフを作る
import torch
from torch_geometric.data import Data

edge_index = torch.tensor([[0, 1, 1, 2],
                           [1, 0, 2, 1]]) #, dtype=torch.long)
x = torch.tensor([[-1], [0], [1]]) #, dtype=torch.float)

data = Data(x=x, edge_index=edge_index)

In [4]:
data

Data(x=[3, 1], edge_index=[2, 4])

In [8]:
# ネガティブサンプリング
from torch_geometric.utils import negative_sampling

negative_sampling(edge_index=data.edge_index, num_nodes=data.num_nodes,
                  num_neg_samples=None, method='sparse')

tensor([[0, 2],
        [2, 0]])

---
## ノードが４つのグラフを作る
`edge_index` は `negative_sampling` のソースコードに掲載されている例を用いる

https://pytorch-geometric.readthedocs.io/en/latest/_modules/torch_geometric/utils/negative_sampling.html

In [9]:
# 適当なグラフを作る
edge_index = torch.as_tensor([[0, 0, 1, 2],
                              [0, 1, 2, 3]])
x = torch.tensor([[-1], [0], [1], [2]])
data = Data(x=x, edge_index=edge_index)

In [10]:
# ネガティブサンプリング
negative_sampling(edge_index=data.edge_index, num_nodes=data.num_nodes,
                  num_neg_samples=None, method='sparse')

tensor([[2, 0, 1, 2],
        [0, 3, 3, 1]])

In [13]:
negative_sampling(edge_index=data.edge_index, num_nodes=data.num_nodes,
                  num_neg_samples=None, method='sparse')

tensor([[1, 1, 0, 3],
        [0, 3, 3, 0]])

---
要は，グラフに存在しないエッジを（適当な本数だけ）生成するのが negative_sampling と思える。

`num_neg_samples` は，生成したいエッジの個数を指定する。
`num_neg_samples=None` とすると，適当な(approximate)値がセットされる。

method に指定できるのは 'sprase' と 'dense’の２通り (default:'sparse'。  
negative_sampling のソースコードによると
- "sparse" : will work on any graph of any size, while
- "dense" :  can perform faster true-negative checks.
            
            